# Generated by Django 2.0.4 on 2018-04-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaboard', '0002_auto_20180418_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
