# Generated by Django 2.0.4 on 2018-04-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaboard', '0003_auto_20180418_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
