# Generated by Django 2.0.4 on 2018-04-18 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaboard', '0004_auto_20180418_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(help_text='Select a user for this book', to=settings.AUTH_USER_MODEL),
        ),
    ]
