# Generated by Django 2.0.4 on 2018-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaboard', '0005_auto_20180418_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
